### ISSUE TITLE
Praise for your excellent work and inquiry about future updates.

### ISSUE THREAD

**Issue by honeymagico** [nibasya/MozjpegGUI#1]
I wanted to express my appreciation for the amazing work you've done with MozjpegGUI. 
It's a fantastic tool that has greatly improved my workflow. 
I wanted to inquire if you have any plans to updates MozjpegGui to use mozjpeg V4.

Keep up the great work! 😄

**Comment by nibasya** [comment]
Initiated V3.3.1 -> V4.1.1 update.
Now checking what kind of changes has been made to the codes.
Quite numerous, this will take time...

**Comment by nibasya** [comment]
Following updates will be applied.
zlib 1.2.11 -> 1.3
libpng 1637 -> 1640
mozjpeg 3.3.1 -> 4.1.1

**Comment by nibasya** [comment]
Released ver. 1.4.
Closing this ticket.
