### ISSUE TITLE
App crashing after processing some images

### ISSUE THREAD

**Issue by TahminRomit** [nibasya/MozjpegGUI#2]
I am not sure what the problem is; the app crashes without showing any warning after processing 60/70 images. Although it was working the night before,

To reproduce this, I changed the directories and tried different images. Nothing worked. Thanks.

**Comment by nibasya** [comment]
Sorry for late reply.
Any example of the files which will let the app crash?
Or, any other information such as input file type(jpg, png, bmp, etc)?

**Comment by nibasya** [comment]
Found 1 example of a crush, when using a gif as an input.
Will be fixed in next release.

**Comment by nibasya** [comment]
Released ver. 1.4 which might help you.
Please create another ticket if you still have a trouble.
